---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart PgBouncer
  ansible.builtin.systemd:
    name: "pgbouncer@{{ item }}"
    state: restarted
  loop: "{{ range(1, pgbouncer_process_count + 1) | list }}"
  failed_when: false
